services:
  # MySQL Database
  mysql:
    image: mysql:latest
    container_name: medical-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-medical_management}
      MYSQL_USER: ${DB_USERNAME:-medical_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpassword}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - medical-network

volumes:
  mysql_data:
    driver: local

networks:
  medical-network:
    driver: bridge
